from selenium.webdriver.common.by import By


class LocatorBasePages:

    BUTTON_RECOVER_PASSWORD = (By.CSS_SELECTOR, "a[href='/forgot-password']")
    BUTTON_RECOVER = (By.XPATH, "//button[text()='Восстановить']")
    BUTTON_SHOW_PASSWORD = (By.CSS_SELECTOR, "div.input_type_password div svg path")
    BUTTON_PERSONAL_ACCOUNT = (By.CSS_SELECTOR, "a[href='/account'] p")
    BUTTON_ORDER_HISTORY = (By.CSS_SELECTOR, "a[href='/account/order-history']")
    BUTTON_EXIT_PERSONAL_ACCOUNT = (By.XPATH, "//button[contains(text(),'Выход')]")
    BUTTON_ENTER_PERSONAL_ACCOUNT = (By.XPATH, "//button[contains(text(),'Войти')]")
    BUTTON_DESIGNER = (By.CSS_SELECTOR, "a[class^='AppHeader'][href='/']")
    BUTTON_ORDERS_FEED = (By.CSS_SELECTOR, "a[href='/feed']")
    BUTTON_ANY_INGREDIENT = (By.CSS_SELECTOR, "a[class^='BurgerIngredient']")
    BUTTON_CLOSE_INFO_INGREDIENT = (By.CSS_SELECTOR, "section[class^='Modal_modal_opened'] button")
    BUTTON_PLACE_ORDER = (By.XPATH, "//button[text()='Оформить заказ']")
    BUTTON_SAVE_IN_RECOVER_PASSWORD = (By.XPATH, "//button[contains(text(),'Сохранить')]")
    FIELD_INPUT_EMAIL = (By.XPATH, "//label[text()='Email']/following-sibling::input[1]")
    FIELD_INPUT_PASSWORD = (By.XPATH, "//label[text()='Пароль']/following-sibling::input[1]")
    FIELD_INPUT_PASSWORD_IS_ACTIVE = (By.XPATH, "//label[text()='Пароль']")
    FIELD_BURGER_CONSTRUCTOR = (By.CSS_SELECTOR, "section[class^='BurgerConstructor'] ul")
    COUNTER_ANY_INGREDIENT = (By.CSS_SELECTOR, "p[class^='counter']")
    COUNTER_ORDERS_ALL_TIME = (By.XPATH, "//p[text()='Выполнено за все время:']/following-sibling::p[1]")
    COUNTER_ORDERS_FOR_TODAY = (By.XPATH, "//p[text()='Выполнено за сегодня:']/following-sibling::p[1]")
    ORDER_IN_PROGRESS_SECTION = (By.CSS_SELECTOR, "ul[class^='OrderFeed_orderListReady']")
    NAME_RECOVER_PASSWORD = (By.XPATH, "//h2[text()='Восстановление пароля']")
    NAME_ENTER_IN_PERSONAL_ACCOUNT = (By.XPATH, "//h2[text()='Вход']")
    NAME_ID_ORDER = (By.XPATH, "//p[text()='идентификатор заказа']")
    ANY_INGREDIENT = (By.CSS_SELECTOR, "a[class^='BurgerIngr'] img")
    ANY_ORDER_HISTORY = (By.CSS_SELECTOR, "a[class^='OrderHistory']")
    NUMBER_ORDER = (By.CSS_SELECTOR, "div[class^='Modal'] h2")
    NUMBER_ORDER_IN_ORDER_FEED = (By.CSS_SELECTOR, "div[class^='OrderHistory'] p")
    NUMBER_IN_WORK = (By.CSS_SELECTOR, "ul[class^='OrderFeed_orderListReady'] li")
    POP_UP_WINDOW_ORDER_DETAILS = (By.XPATH, "//h2[text()='Детали ингредиента']")
    POP_UP_WINDOW_ORDER_NUMBER = (By.CSS_SELECTOR, "div[class^='Modal_orderBox']")
    DISPLAYING_CHECKMARK = (By.CSS_SELECTOR, "div[class^='Modal_modal__contentBox'] h2")
